---
name: "rpvlan_new_mac_auth_failure"
pack: "campus_ztp"
enabled: true
description: "notification that a device has succeded to mac authenticate"
trigger:
  type: "campus_ztp.rpvlan_new_mac_auth_success"
action:
  ref: "campus_ztp.rpvlan_process_new_mac_auth_success_chain"
  parameters:
    device: "{{trigger.device}}"
    mac: "{{trigger.mac}}"
    port: "{{trigger.port}}"
