---
name: "rpvlan_new_mac_auth_failure_do_not_allow"
pack: "campus_ztp"
enabled: true
description: "notification that a device has failed to mac authenticate and should not be allowed to authenticate"
trigger:
  type: "campus_ztp.rpvlan_new_mac_auth_failure_do_not_allow"
action:
  ref: "campus_ztp.rpvlan_process_new_mac_auth_failure_do_not_allow_chain"
  parameters:
    ip: "{{trigger.ip}}"
    ap_name: "{{trigger.ap_name}}"
    mac: "{{trigger.mac}}"
    port: "{{trigger.port}}"
